name: Publish Package

on:
  push:
    branches:
      - 'main'        # Trigger on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Authenticate to GitHub Packages
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build  # if you have a build step
      - name: Help
        run: cat .npmrc

      - name: Publish package
        run: npm publish